[tool.poetry]
name = "open-transit-py"
version = "0.1.0"
description = ""
authors = ["Dmitry Semenov <lonelyteapot@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
